### ISSUE TITLE
About normalize bulk and sc data

### ISSUE THREAD

**Issue by Ahawywyw** [sunduanchen/Scissor#29]
Hi!
Thank you for the nice tools.
In scissor, we use normalize.quantiles to normalize bulk and sc data.
While I am wondering  if we can normalize original bulk and sc count data.Thanks a lot!

**Comment by sunduanchen** [comment]
Hi,

For single-cell data, we recommend using some preprocessing steps in Seurat. It may not be applicable to perform quantile normalization on original count data.

Besides, I think you can even try other approaches to normalize original bulk and single-cell data separately. Different normalization approaches may have better performances in different applications.

We tried several normalizations and batch-effect removing techniques (such as function in 'combat' R packages) to explore Scissor's preliminary results. Finally, we used the quantile normalization in our tool since the corresponding results have more biologically meaningful cell subpopulations.

Hope these helps.

Best,
Duanchen
