### ISSUE TITLE
invalid 'ncol' value (too large or NA)

### ISSUE THREAD

**Issue by MTutino** [sunduanchen/Scissor#9]
Hi,

I am trying to use Scissor with family "binomial" on a dataset of bulk RNAseq with 43 samples (11 controls and 32 cases) and publicly available scRNAseq with 5092 cells. I receive the following error message

[1] "|**************************************************|"
[1] "Performing quality-check for the correlations"
[1] "The five-number summary of correlations:"
       0%       25%       50%       75%      100% 
0.3543059 0.4483379 0.4650750 0.4824858 0.6122901 
[1] "|**************************************************|"
[1] "Current phenotype contains 11 healthy and 32 asthmatics samples."
[1] "Perform logistic regression on the given phenotypes:"
Error in matrix(NA, nrow = nfolds, ncol = numi2) : 
  invalid 'ncol' value (too large or NA)
In addition: Warning messages:
1: In Scissor(mat, sc_dataset, as.matrix(pheno), tag = tag, alpha = 0.2,  :
  NAs introduced by coercion
2: In matrix(sapply(outi, function(x) { :
  data length [10] is not a sub-multiple or multiple of the number of rows [5093]
3: In matrix(sapply(outi, function(x) { :
  data length [10] is not a sub-multiple or multiple of the number of rows [5093]

Could you please help?

Thank you

**Comment by sunduanchen** [comment]
Can you share me your data and let me have a try?

Thanks,
Duanchen

**Comment by MTutino** [comment]
I found out what the issue was. I was using the binomial test and I was supplying the phenotype as a 2-column matrix, first column was sample IDs and second column was the phenotype, instead of a vector of binary phenotypes. Scissor started fine, it returned the five-number summary of correlations and the number of cases and controls. Only after starting the logistic regression it would fail with the error reported above. I only understood where the issue was when I used the example data from the tutorial. I think it would be helpful to specify what the phenotype input should be in the tutorial and, possibly, exit with an error if the wrong input type is used. 
Thank you for the great tool though!

**Comment by sunduanchen** [comment]
Glad to know you work it out. I will make it clear and make a new update based on your suggestion.

Thanks a bunch!!

**Comment by chenx9** [comment]
Hello, I have the same problem, the following is my phenotype information and code, I don't know where the problem is. I hope you can help me. Thank you very much!
> table(phenotype)
phenotype
 0  1 
47 33 
> head(phenotype)
GSM907792 GSM907793 GSM907794 GSM907795 GSM907796 GSM907797 
        1         1         1         1         1         1 

infos4 <- Scissor(bulk_dataset, sc_dataset , phenotype, tag = tag, alpha = 0.5, 
+                   family = "binomial" #因为表型信息是二元的'0','1'信息，故用logistic回归模型
+                   )
[1] "|**************************************************|"
[1] "Performing quality-check for the correlations"
[1] "The five-number summary of correlations:"
          0%          25%          50%          75%         100% 
-0.005203654 -0.001058838  0.000199166  0.001769546  0.075413425 
[1] "|**************************************************|"
[1] "Current phenotype contains 47 Control and 33 AD samples."
[1] "Perform logistic regression on the given phenotypes:"
Error in matrix(NA, nrow = nfolds, ncol = numi2) : 
  invalid 'ncol' value (too large or NA)
In addition: Warning messages:
1: In Scissor(bulk_dataset, sc_dataset, phenotype, tag = tag, alpha = 0.5,  :
  The median correlation between the single-cell and bulk samples is relatively low.
2: In matrix(sapply(outi, function(x) { :
  data length [10] is not a sub-multiple or multiple of the number of rows [2741]
3: In matrix(sapply(outi, function(x) { :
  data length [10] is not a sub-multiple or multiple of the number of rows [2741]

**Comment by liukun2463** [comment]
Hello, I have the same problem, the following is my phenotype information and code, I don't know where the problem is. I hope you can help me. Thank you very much!
phenotype <- group
> group
      Name         Value
 [1,] "GSM4748450" "0"
 [2,] "GSM4748451" "0"
 [3,] "GSM4748452" "0"
 [4,] "GSM4748453" "0"
 [5,] "GSM4748454" "0"
 [6,] "GSM4748455" "0"
 [7,] "GSM4748456" "0"
 [8,] "GSM4748457" "0"
 [9,] "GSM4748458" "0"
[10,] "GSM4748459" "0"
[11,] "GSM4748460" "0"
[12,] "GSM4748461" "0"
[13,] "GSM4748462" "0"
[14,] "GSM4748463" "0"
[15,] "GSM4748464" "1"
[16,] "GSM4748465" "1"
[17,] "GSM4748466" "1"
[18,] "GSM4748467" "1"
[19,] "GSM4748468" "1"
[20,] "GSM4748469" "1"
[21,] "GSM4748470" "1"
[22,] "GSM4748471" "1"
[23,] "GSM4748472" "1"
[24,] "GSM4748473" "1"
[25,] "GSM4748474" "1"
[26,] "GSM4748475" "1"
[27,] "GSM4748476" "1"
[28,] "GSM4748477" "1"
[29,] "GSM4748478" "1"
[30,] "GSM4748479" "1"
[31,] "GSM4748480" "1"
[32,] "GSM4748481" "1"
[33,] "GSM4748482" "1"
[34,] "GSM4748483" "1"
[35,] "GSM4748484" "1"
[36,] "GSM4748485" "1"
[37,] "GSM4748486" "1"
[38,] "GSM4748487" "1"
[39,] "GSM4748488" "1"

tag <- c('control', 'obesity')
infos1 <- Scissor(bulk_dataset, sc_dataset1, phenotype, tag = tag, alpha = 0.2, 
                  family = "binomial", Save_file = "Scissor.RData")
[1] "|**************************************************|"
[1] "Performing quality-check for the correlations"
[1] "The five-number summary of correlations:"
        0%        25%        50%        75%       100%
0.02773082 0.23407524 0.26827595 0.35277594 0.53800814
[1] "|**************************************************|"
[1] "Current phenotype contains 14 control and 25 obesity samples."
[1] "Perform logistic regression on the given phenotypes:"
Error in matrix(NA, nrow = nfolds, ncol = numi2) :
  invalid 'ncol' value (too large or NA)

**Comment by liukun2463** [comment]
> Hello, I have the same problem. Have you solved this problem?
Could you help me? Thank you very much!

**Comment by liukun2463** [comment]
> > Hello, I have the same problem. Have you solved this problem?
> > Could you help me? Thank you very much!

phenotype=read.table(inputFile2,sep="\t",header=T,check.names=F)
phenotype=as.matrix(phenotype)
phenotype
class(phenotype)
phenotype=apply(phenotype,2,as.numeric)#将matrix转化成numeric
     GSM4748450 GSM4748451 GSM4748452 GSM4748453 GSM4748454 GSM4748455
[1,]          0          0          0          0          0          0
     GSM4748456 GSM4748457 GSM4748458 GSM4748459 GSM4748460 GSM4748461
[1,]          0          0          0          0          0          0
     GSM4748462 GSM4748463 GSM4748464 GSM4748465 GSM4748466 GSM4748467
[1,]          0          0          1          1          1          1
     GSM4748468 GSM4748469 GSM4748470 GSM4748471 GSM4748472 GSM4748473
[1,]          1          1          1          1          1          1
     GSM4748474 GSM4748475 GSM4748476 GSM4748477 GSM4748478 GSM4748479
[1,]          1          1          1          1          1          1
     GSM4748480 GSM4748481 GSM4748482 GSM4748483 GSM4748484 GSM4748485
[1,]          1          1          1          1          1          1
     GSM4748486 GSM4748487 GSM4748488
[1,]          1          1          1
[1] "matrix" "array"
> tag <- c('control', 'obesity')
> infos1 <- Scissor(bulk_dataset, sc_dataset1, phenotype, tag = tag, alpha = 0.2,
                  family = "binomial", Save_file = "Scissor.RData")
[1] "|**************************************************|"
[1] "Performing quality-check for the correlations"
[1] "The five-number summary of correlations:"
        0%        25%        50%        75%       100%
0.04852072 0.25830852 0.27764791 0.30061563 0.54160975
[1] "|**************************************************|"
[1] "Current phenotype contains 14 control and 25 obesity samples."
[1] "Perform logistic regression on the given phenotypes:"
Error in matrix(NA, nrow = nfolds, ncol = numi2) :
  invalid 'ncol' value (too large or NA)
In addition: Warning messages:
1: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 4.0 GiB
2: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 18.4 GiB
3: In Scissor(bulk_dataset, sc_dataset1, phenotype, tag = tag, alpha = 0.2,  :
  NAs introduced by coercion
4: In matrix(sapply(outi, function(x) { :
  data length [10] is not a sub-multiple or multiple of the number of rows [49701]
5: In matrix(sapply(outi, function(x) { :
  data length [10] is not a sub-multiple or multiple of the number of rows [49701]

**Comment by WaterDrop-EarthDivision** [comment]
@liukun2463   @zzj2024
I encountered the same problem. For me, after investigation, I found that the issue lay in this error message.
`2: In cor(Expression_bulk, Expression_cell) :
the standard deviation is zero`
This led to the inability to build the matrix properly later
`X < -cor (Expression_bulk, Expression_cell) `
 so I added exception handling 
```
if (any(is.na(X)))
warning("include NA value, fill with 0")
X[is.na(X)] <- 0
```
Then it can run normally. The complete code is as follows:

```
Scissor2 = function (bulk_dataset, sc_dataset, phenotype, tag = NULL, alpha = NULL,
                     cutoff = 0.2, family = c("gaussian", "binomial", "cox"),
                     Save_file = "Scissor_inputs.RData", Load_file = NULL)
{
  library(Seurat)
  library(Matrix)
  library(preprocessCore)
  if (is.null(Load_file)) {
    common <- intersect(rownames(bulk_dataset), rownames(sc_dataset))
    if (length(common) == 0) {
      stop("There is no common genes between the given single-cell and bulk samples.")
    }
    if (class(sc_dataset) == "Seurat") {
      sc_exprs <- as.matrix(sc_dataset@assays$RNA@data)
      network <- as.matrix(sc_dataset@graphs$RNA_snn)
    }
    else {
      sc_exprs <- as.matrix(sc_dataset)
      Seurat_tmp <- CreateSeuratObject(sc_dataset)
      Seurat_tmp <- FindVariableFeatures(Seurat_tmp, selection.method = "vst",
                                         verbose = F)
      Seurat_tmp <- ScaleData(Seurat_tmp, verbose = F)
      Seurat_tmp <- RunPCA(Seurat_tmp, features = VariableFeatures(Seurat_tmp),
                           verbose = F)
      Seurat_tmp <- FindNeighbors(Seurat_tmp, dims = 1:10,
                                  verbose = F)
      network <- as.matrix(Seurat_tmp@graphs$RNA_snn)
    }
    diag(network) <- 0
    network[which(network != 0)] <- 1
    dataset0 <- cbind(bulk_dataset[common, ], sc_exprs[common,
    ])
    dataset1 <- normalize.quantiles(as.matrix(dataset0))
    rownames(dataset1) <- rownames(dataset0)
    colnames(dataset1) <- colnames(dataset0)
    Expression_bulk <- dataset1[, 1:ncol(bulk_dataset)]
    Expression_cell <- dataset1[, (ncol(bulk_dataset) +
                                     1):ncol(dataset1)]
    
    X <- cor(Expression_bulk, Expression_cell)
    # 处理 NA 值
    if (any(is.na(X))) {
      warning("include NA value，fill with 0")
      X[is.na(X)] <- 0
    }
    quality_check <- quantile(X,na.rm=TRUE)
    # quality_check <- quantile(X)
    print("|**************************************************|")
    print("Performing quality-check for the correlations")
    print("The five-number summary of correlations:")
    print(quality_check)
    print("|**************************************************|")
    if (quality_check[3] < 0.01) {
      warning("The median correlation between the single-cell and bulk samples is relatively low.")
    }
    if (family == "binomial") {
      Y <- as.numeric(phenotype)
      z <- table(Y)
      if (length(z) != length(tag)) {
        stop("The length differs between tags and phenotypes. Please check Scissor inputs and selected regression type.")
      }
      else {
        print(sprintf("Current phenotype contains %d %s and %d %s samples.",
                      z[1], tag[1], z[2], tag[2]))
        print("Perform logistic regression on the given phenotypes:")
      }
    }
    if (family == "gaussian") {
      Y <- as.numeric(phenotype)
      z <- table(Y)
      if (length(z) != length(tag)) {
        stop("The length differs between tags and phenotypes. Please check Scissor inputs and selected regression type.")
      }
      else {
        tmp <- paste(z, tag)
        print(paste0("Current phenotype contains ",
                     paste(tmp[1:(length(z) - 1)], collapse = ", "),
                     ", and ", tmp[length(z)], " samples."))
        print("Perform linear regression on the given phenotypes:")
      }
    }
    if (family == "cox") {
      Y <- as.matrix(phenotype)
      if (ncol(Y) != 2) {
        stop("The size of survival data is wrong. Please check Scissor inputs and selected regression type.")
      }
      else {
        print("Perform cox regression on the given clinical outcomes:")
      }
    }
    save(X, Y, network, Expression_bulk, Expression_cell,
         file = Save_file)
  }
  else {
    load(Load_file)
  }
  if (is.null(alpha)) {
    alpha <- c(0.005, 0.01, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5,
               0.6, 0.7, 0.8, 0.9)
  }
  for (i in 1:length(alpha)) {
    set.seed(123)
    # print(X)
    # print(Y)
    # print(ncol(X))
    fit0 <- APML1(X, Y, family = family, penalty = "Net",
                  alpha = alpha[i], Omega = network, nlambda = 100,
                  nfolds = min(10, nrow(X)))
    fit1 <- APML1(X, Y, family = family, penalty = "Net",
                  alpha = alpha[i], Omega = network, lambda = fit0$lambda.min)
    if (family == "binomial") {
      Coefs <- as.numeric(fit1$Beta[2:(ncol(X) + 1)])
    }
    else {
      Coefs <- as.numeric(fit1$Beta)
    }
    Cell1 <- colnames(X)[which(Coefs > 0)]
    Cell2 <- colnames(X)[which(Coefs < 0)]
    percentage <- (length(Cell1) + length(Cell2))/ncol(X)
    print(sprintf("alpha = %s", alpha[i]))
    print(sprintf("Scissor identified %d Scissor+ cells and %d Scissor- cells.",
                  length(Cell1), length(Cell2)))
    print(sprintf("The percentage of selected cell is: %s%%",
                  formatC(percentage * 100, format = "f", digits = 3)))
    if (percentage < cutoff) {
      break
    }
    cat("\n")
  }
  print("|**************************************************|")
  return(list(para = list(alpha = alpha[i], lambda = fit0$lambda.min,
                          family = family), Coefs = Coefs, Scissor_pos = Cell1,
              Scissor_neg = Cell2))
}
```

hope this can be of help to those who come after
